export type Protocol = 'tcp' | 'udp' | 'sctp' | 'tcp/udp';

export interface PortEntry {
  port: number
  service: string
  protocol: Protocol
  description: string
}

// Curated set of well-known and registered ports developers actually encounter.
// Sourced from IANA service-name-port-number registry; trimmed to common entries.
export const WELL_KNOWN_PORTS: PortEntry[] = [
  { port: 7, service: 'echo', protocol: 'tcp/udp', description: 'Echo Protocol' },
  { port: 13, service: 'daytime', protocol: 'tcp/udp', description: 'Daytime Protocol' },
  { port: 19, service: 'chargen', protocol: 'tcp/udp', description: 'Character Generator' },
  { port: 20, service: 'ftp-data', protocol: 'tcp', description: 'FTP — data transfer' },
  { port: 21, service: 'ftp', protocol: 'tcp', description: 'FTP — control (command)' },
  { port: 22, service: 'ssh', protocol: 'tcp', description: 'Secure Shell, scp, sftp, ssh tunneling' },
  { port: 23, service: 'telnet', protocol: 'tcp', description: 'Telnet — unencrypted text communications' },
  { port: 25, service: 'smtp', protocol: 'tcp', description: 'Simple Mail Transfer Protocol — server-to-server' },
  { port: 37, service: 'time', protocol: 'tcp/udp', description: 'Time Protocol' },
  { port: 43, service: 'whois', protocol: 'tcp', description: 'WHOIS protocol' },
  { port: 49, service: 'tacacs', protocol: 'tcp/udp', description: 'TACACS authentication' },
  { port: 53, service: 'domain (DNS)', protocol: 'tcp/udp', description: 'Domain Name System' },
  { port: 67, service: 'bootps / dhcp-server', protocol: 'udp', description: 'BOOTP / DHCP server' },
  { port: 68, service: 'bootpc / dhcp-client', protocol: 'udp', description: 'BOOTP / DHCP client' },
  { port: 69, service: 'tftp', protocol: 'udp', description: 'Trivial File Transfer Protocol' },
  { port: 80, service: 'http', protocol: 'tcp', description: 'Hypertext Transfer Protocol' },
  { port: 88, service: 'kerberos', protocol: 'tcp/udp', description: 'Kerberos authentication' },
  { port: 110, service: 'pop3', protocol: 'tcp', description: 'Post Office Protocol v3' },
  { port: 111, service: 'sunrpc / portmap', protocol: 'tcp/udp', description: 'ONC RPC (Sun RPC) portmapper' },
  { port: 113, service: 'ident', protocol: 'tcp', description: 'Identification Protocol' },
  { port: 119, service: 'nntp', protocol: 'tcp', description: 'Network News Transfer Protocol' },
  { port: 123, service: 'ntp', protocol: 'udp', description: 'Network Time Protocol' },
  { port: 135, service: 'msrpc / epmap', protocol: 'tcp/udp', description: 'Microsoft RPC EPMAP' },
  { port: 137, service: 'netbios-ns', protocol: 'tcp/udp', description: 'NetBIOS Name Service' },
  { port: 138, service: 'netbios-dgm', protocol: 'udp', description: 'NetBIOS Datagram Service' },
  { port: 139, service: 'netbios-ssn', protocol: 'tcp', description: 'NetBIOS Session Service' },
  { port: 143, service: 'imap', protocol: 'tcp', description: 'Internet Message Access Protocol' },
  { port: 161, service: 'snmp', protocol: 'udp', description: 'Simple Network Management Protocol' },
  { port: 162, service: 'snmptrap', protocol: 'tcp/udp', description: 'SNMP trap' },
  { port: 179, service: 'bgp', protocol: 'tcp', description: 'Border Gateway Protocol' },
  { port: 194, service: 'irc', protocol: 'tcp', description: 'Internet Relay Chat' },
  { port: 220, service: 'imap3', protocol: 'tcp/udp', description: 'IMAP version 3' },
  { port: 389, service: 'ldap', protocol: 'tcp/udp', description: 'Lightweight Directory Access Protocol' },
  { port: 443, service: 'https', protocol: 'tcp', description: 'HTTP over TLS/SSL' },
  { port: 445, service: 'microsoft-ds / smb', protocol: 'tcp', description: 'Microsoft-DS SMB file sharing' },
  { port: 465, service: 'smtps (submissions)', protocol: 'tcp', description: 'SMTP over implicit TLS (submission)' },
  { port: 500, service: 'isakmp', protocol: 'udp', description: 'IPsec Internet Key Exchange' },
  { port: 514, service: 'syslog', protocol: 'udp', description: 'Syslog' },
  { port: 515, service: 'lpd / printer', protocol: 'tcp', description: 'Line Printer Daemon' },
  { port: 520, service: 'rip', protocol: 'udp', description: 'Routing Information Protocol' },
  { port: 521, service: 'ripng', protocol: 'udp', description: 'RIP next generation (IPv6)' },
  { port: 540, service: 'uucp', protocol: 'tcp', description: 'Unix-to-Unix Copy' },
  { port: 546, service: 'dhcpv6-client', protocol: 'tcp/udp', description: 'DHCPv6 client' },
  { port: 547, service: 'dhcpv6-server', protocol: 'tcp/udp', description: 'DHCPv6 server' },
  { port: 554, service: 'rtsp', protocol: 'tcp/udp', description: 'Real Time Streaming Protocol' },
  { port: 587, service: 'submission', protocol: 'tcp', description: 'SMTP message submission with STARTTLS' },
  { port: 631, service: 'ipp / cups', protocol: 'tcp', description: 'Internet Printing Protocol' },
  { port: 636, service: 'ldaps', protocol: 'tcp', description: 'LDAP over TLS/SSL' },
  { port: 873, service: 'rsync', protocol: 'tcp', description: 'rsync file synchronization' },
  { port: 989, service: 'ftps-data', protocol: 'tcp', description: 'FTPS — data over TLS' },
  { port: 990, service: 'ftps', protocol: 'tcp', description: 'FTPS — control over TLS' },
  { port: 992, service: 'telnets', protocol: 'tcp', description: 'Telnet over TLS' },
  { port: 993, service: 'imaps', protocol: 'tcp', description: 'IMAP over TLS' },
  { port: 995, service: 'pop3s', protocol: 'tcp', description: 'POP3 over TLS' },
  { port: 1080, service: 'socks', protocol: 'tcp', description: 'SOCKS proxy' },
  { port: 1194, service: 'openvpn', protocol: 'tcp/udp', description: 'OpenVPN' },
  { port: 1433, service: 'ms-sql-s', protocol: 'tcp', description: 'Microsoft SQL Server' },
  { port: 1521, service: 'oracle', protocol: 'tcp', description: 'Oracle database default listener' },
  { port: 1701, service: 'l2tp', protocol: 'udp', description: 'Layer 2 Tunneling Protocol' },
  { port: 1723, service: 'pptp', protocol: 'tcp', description: 'Point-to-Point Tunneling Protocol' },
  { port: 1812, service: 'radius', protocol: 'udp', description: 'RADIUS authentication' },
  { port: 1813, service: 'radius-acct', protocol: 'udp', description: 'RADIUS accounting' },
  { port: 1883, service: 'mqtt', protocol: 'tcp', description: 'MQTT — message queue telemetry transport' },
  { port: 2049, service: 'nfs', protocol: 'tcp/udp', description: 'Network File System' },
  { port: 2181, service: 'zookeeper', protocol: 'tcp', description: 'Apache ZooKeeper' },
  { port: 2375, service: 'docker', protocol: 'tcp', description: 'Docker REST API (unencrypted)' },
  { port: 2376, service: 'docker-tls', protocol: 'tcp', description: 'Docker REST API over TLS' },
  { port: 2379, service: 'etcd-client', protocol: 'tcp', description: 'etcd client API' },
  { port: 2380, service: 'etcd-server', protocol: 'tcp', description: 'etcd peer communication' },
  { port: 3000, service: 'dev (Node, Rails, Grafana)', protocol: 'tcp', description: 'Common dev-server default (Node, Rails, Grafana)' },
  { port: 3001, service: 'dev (alt)', protocol: 'tcp', description: 'Common alternative dev-server port' },
  { port: 3306, service: 'mysql', protocol: 'tcp', description: 'MySQL / MariaDB' },
  { port: 3389, service: 'rdp', protocol: 'tcp/udp', description: 'Remote Desktop Protocol' },
  { port: 4369, service: 'epmd', protocol: 'tcp', description: 'Erlang Port Mapper Daemon' },
  { port: 4444, service: 'krb524 / metasploit', protocol: 'tcp', description: 'Default Metasploit listener / Kerberos v5 to v4' },
  { port: 4789, service: 'vxlan', protocol: 'udp', description: 'VXLAN' },
  { port: 5000, service: 'flask / docker-registry', protocol: 'tcp', description: 'Flask default, Docker Registry, AirPlay receiver (macOS 12+)' },
  { port: 5060, service: 'sip', protocol: 'tcp/udp', description: 'Session Initiation Protocol' },
  { port: 5061, service: 'sips', protocol: 'tcp', description: 'SIP over TLS' },
  { port: 5222, service: 'xmpp-client', protocol: 'tcp', description: 'XMPP client connection' },
  { port: 5269, service: 'xmpp-server', protocol: 'tcp', description: 'XMPP server-to-server' },
  { port: 5353, service: 'mdns', protocol: 'udp', description: 'Multicast DNS (Bonjour, Avahi)' },
  { port: 5432, service: 'postgresql', protocol: 'tcp', description: 'PostgreSQL' },
  { port: 5601, service: 'kibana', protocol: 'tcp', description: 'Kibana' },
  { port: 5672, service: 'amqp', protocol: 'tcp', description: 'AMQP (RabbitMQ)' },
  { port: 5900, service: 'vnc', protocol: 'tcp', description: 'VNC Remote Frame Buffer' },
  { port: 5984, service: 'couchdb', protocol: 'tcp', description: 'CouchDB' },
  { port: 6000, service: 'x11', protocol: 'tcp', description: 'X Window System' },
  { port: 6379, service: 'redis', protocol: 'tcp', description: 'Redis key-value store' },
  { port: 6443, service: 'kubernetes-api', protocol: 'tcp', description: 'Kubernetes API server' },
  { port: 6660, service: 'irc', protocol: 'tcp', description: 'IRC (alt)' },
  { port: 6667, service: 'irc', protocol: 'tcp', description: 'IRC' },
  { port: 7000, service: 'cassandra', protocol: 'tcp', description: 'Cassandra inter-node' },
  { port: 7077, service: 'spark-master', protocol: 'tcp', description: 'Apache Spark master' },
  { port: 8000, service: 'http-alt / dev', protocol: 'tcp', description: 'Common HTTP alternative / Django default' },
  { port: 8008, service: 'http-alt', protocol: 'tcp', description: 'HTTP alternative' },
  { port: 8080, service: 'http-proxy', protocol: 'tcp', description: 'HTTP alternative / proxies / Tomcat / Jenkins' },
  { port: 8081, service: 'http-alt', protocol: 'tcp', description: 'Common HTTP alternative' },
  { port: 8086, service: 'influxdb', protocol: 'tcp', description: 'InfluxDB HTTP API' },
  { port: 8088, service: 'http / hadoop-rm', protocol: 'tcp', description: 'Hadoop ResourceManager web UI' },
  { port: 8443, service: 'https-alt', protocol: 'tcp', description: 'HTTPS alternative / Tomcat SSL' },
  { port: 8888, service: 'jupyter / http-alt', protocol: 'tcp', description: 'Jupyter Notebook / HTTP alternative' },
  { port: 9000, service: 'sonarqube / php-fpm', protocol: 'tcp', description: 'SonarQube / PHP-FPM / portainer' },
  { port: 9042, service: 'cassandra-cql', protocol: 'tcp', description: 'Cassandra CQL native protocol' },
  { port: 9090, service: 'prometheus', protocol: 'tcp', description: 'Prometheus / openSUSE Cockpit' },
  { port: 9092, service: 'kafka', protocol: 'tcp', description: 'Apache Kafka broker' },
  { port: 9100, service: 'jetdirect / node-exporter', protocol: 'tcp', description: 'HP JetDirect printing / Prometheus node-exporter' },
  { port: 9200, service: 'elasticsearch-http', protocol: 'tcp', description: 'Elasticsearch HTTP' },
  { port: 9300, service: 'elasticsearch-transport', protocol: 'tcp', description: 'Elasticsearch transport' },
  { port: 9418, service: 'git', protocol: 'tcp', description: 'Git protocol' },
  { port: 11211, service: 'memcached', protocol: 'tcp/udp', description: 'memcached' },
  { port: 15672, service: 'rabbitmq-mgmt', protocol: 'tcp', description: 'RabbitMQ management UI' },
  { port: 25565, service: 'minecraft', protocol: 'tcp', description: 'Minecraft server' },
  { port: 27017, service: 'mongodb', protocol: 'tcp', description: 'MongoDB' },
  { port: 27018, service: 'mongodb-shard', protocol: 'tcp', description: 'MongoDB shard server' },
  { port: 27019, service: 'mongodb-config', protocol: 'tcp', description: 'MongoDB config server' },
  { port: 50000, service: 'sap', protocol: 'tcp', description: 'SAP NetWeaver default' },
  { port: 50070, service: 'hadoop-namenode', protocol: 'tcp', description: 'Hadoop HDFS NameNode web UI (legacy)' },
];
