// Curated subset of templates derived from github/gitignore (CC0)
// and toptal.com/developers/gitignore. Kept minimal & offline.

export interface GitignoreTemplate {
  id: string
  name: string
  content: string
}

export const TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'node',
    name: 'Node',
    content: `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage
coverage
*.lcov
.nyc_output

# Dependency directories
node_modules/
jspm_packages/

# Build output
dist/
build/
out/
.next/
.nuxt/
.cache/
.parcel-cache/

# Optional
.npm
.eslintcache
.stylelintcache
.node_repl_history

# yarn v2
.yarn/cache
.yarn/install-state.gz
.pnp.*
`,
  },
  {
    id: 'python',
    name: 'Python',
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Tooling
.pytest_cache/
.tox/
.nox/
.coverage
.coverage.*
htmlcov/
.cache
.hypothesis/
.mypy_cache/
.pyre/
.pytype/
.ruff_cache/

# Notebooks
.ipynb_checkpoints
`,
  },
  {
    id: 'go',
    name: 'Go',
    content: `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with \`go test -c\`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum

# Build cache
bin/
`,
  },
  {
    id: 'rust',
    name: 'Rust',
    content: `# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb
`,
  },
  {
    id: 'java',
    name: 'Java',
    content: `*.class
*.log
*.ctxt
.mtj.tmp/
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar
hs_err_pid*
replay_pid*

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle
build/
!gradle/wrapper/gradle-wrapper.jar
!**/src/main/**/build/
!**/src/test/**/build/
gradle-app.setting
.gradletasknamecache
`,
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    content: `# Kotlin
*.class

# Gradle
.gradle/
build/

# IntelliJ
*.iml
.idea/
out/

# KMP / KMM
**/iosApp/Pods/
**/iosApp/Podfile.lock
shared/build/
`,
  },
  {
    id: 'csharp',
    name: 'C# / .NET',
    content: `# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio
.vs/
*.user
*.suo
*.userprefs

# NuGet
*.nupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
`,
  },
  {
    id: 'cpp',
    name: 'C / C++',
    content: `# Compiled object files
*.slo
*.lo
*.o
*.obj

# Compiled dynamic libraries
*.so
*.dylib
*.dll

# Compiled static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app

# Build dirs
build/
cmake-build-*/

# CMake
CMakeCache.txt
CMakeFiles/
CMakeScripts/
cmake_install.cmake
install_manifest.txt
Makefile
`,
  },
  {
    id: 'ruby',
    name: 'Ruby',
    content: `*.gem
*.rbc
.bundle/
.config
.yardoc/
_yardoc/
coverage/
doc/
InstalledFiles
pkg/
spec/reports/
test/tmp/
test/version_tmp/
tmp/

# Rails
.rspec
log/
storage/
public/system
public/uploads
.byebug_history
.dockerignore

# Bundler
vendor/bundle
`,
  },
  {
    id: 'swift',
    name: 'Swift',
    content: `# Xcode
build/
DerivedData/
*.xcodeproj/*
!*.xcodeproj/project.pbxproj
!*.xcodeproj/xcshareddata/
!*.xcworkspace/contents.xcworkspacedata
**/xcshareddata/WorkspaceSettings.xcsettings

# Swift Package Manager
.swiftpm/
Packages/
Package.resolved
.build/

# CocoaPods
Pods/
`,
  },
  {
    id: 'php',
    name: 'PHP',
    content: `# Composer
/vendor/
composer.phar

# Laravel
.env
.env.backup
.phpunit.result.cache
storage/*.key
storage/logs/
storage/framework/cache/
storage/framework/sessions/
storage/framework/views/
bootstrap/cache/

# Symfony
/var/cache/*
/var/log/*
/var/sessions/*
!var/cache/.gitkeep
!var/log/.gitkeep
!var/sessions/.gitkeep
`,
  },
  {
    id: 'elixir',
    name: 'Elixir',
    content: `_build/
cover/
deps/
doc/
.fetch
erl_crash.dump
*.ez
*.beam
/config/*.secret.exs
.elixir_ls/
`,
  },
  {
    id: 'haskell',
    name: 'Haskell',
    content: `dist/
dist-*/
cabal-dev/
*.o
*.hi
*.hie
*.chi
*.chs.h
*.dyn_o
*.dyn_hi
.hpc/
.hsenv/
.cabal-sandbox/
cabal.sandbox.config
*.prof
*.aux
*.hp
*.eventlog
.stack-work/
cabal.project.local
cabal.project.local~
.HTF/
.ghc.environment.*
`,
  },
  {
    id: 'docker',
    name: 'Docker',
    content: `# Local docker
docker-compose.override.yml

# Compose .env file
.env
.env.local

# Build context dirs commonly excluded by .dockerignore but also kept out of git
.docker/
`,
  },
  {
    id: 'terraform',
    name: 'Terraform',
    content: `# Local state
*.tfstate
*.tfstate.*
crash.log
crash.*.log

# Plan output
*.tfplan
*.tfplan.json

# Provider plugins
.terraform/
.terraform.lock.hcl

# CLI variable files (often secrets)
*.tfvars
*.tfvars.json

# Override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json
`,
  },
  {
    id: 'ansible',
    name: 'Ansible',
    content: `*.retry
.vault_pass
*.vault
roles/galaxy/
.ansible/
`,
  },
  {
    id: 'macos',
    name: 'macOS',
    content: `.DS_Store
.AppleDouble
.LSOverride
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
`,
  },
  {
    id: 'windows',
    name: 'Windows',
    content: `# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle bin
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk
`,
  },
  {
    id: 'linux',
    name: 'Linux',
    content: `*~

# Temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

# KDE directory preferences
.directory

# Linux trash folder which might appear on any partition or disk
.Trash-*

# .nfs files are created when an open file is removed but is still being accessed
.nfs*
`,
  },
  {
    id: 'vscode',
    name: 'VS Code',
    content: `.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History for Visual Studio Code
.history/

# Built Visual Studio Code Extensions
*.vsix
`,
  },
  {
    id: 'jetbrains',
    name: 'JetBrains IDEs',
    content: `.idea/
*.iml
*.ipr
*.iws

# CMake
cmake-build-*/

# Sensitive or high-churn files
.idea/workspace.xml
.idea/tasks.xml
.idea/usage.statistics.xml
.idea/dictionaries
.idea/shelf
.idea/sonarlint/
`,
  },
  {
    id: 'vim',
    name: 'Vim',
    content: `# Swap
[._]*.s[a-v][a-z]
!*.svg
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]

# Session
Session.vim
Sessionx.vim

# Temporary
.netrwhist
*~
tags
[._]*.un~
`,
  },
  {
    id: 'emacs',
    name: 'Emacs',
    content: `# -*- mode: gitignore; -*-
*~
\\#*\\#
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.\\#*

# Org
.org-id-locations
*_archive
*_flymake.*

# Backup
*~
.#*
\\#*#

# Cask
.cask/
dist/
flycheck_*.el
`,
  },
  {
    id: 'unity',
    name: 'Unity',
    content: `[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Mm]emoryCaptures/
[Uu]serSettings/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
sysinfo.txt
*.apk
*.aab
*.unitypackage
*.app
crashlytics-build.properties
`,
  },
  {
    id: 'unreal',
    name: 'Unreal Engine',
    content: `# Visual Studio / Rider files
.vs/
.idea/
*.VC.db
*.opensdf
*.opendb
*.sdf
*.sln
*.suo
*.xcodeproj/

# Build / packaging
Binaries/
DerivedDataCache/
Intermediate/
Saved/
Build/
*.target
*.modules
`,
  },
  {
    id: 'tex',
    name: 'LaTeX',
    content: `*.aux
*.bbl
*.bcf
*.blg
*.fdb_latexmk
*.fls
*.lof
*.log
*.lot
*.nav
*.out
*.run.xml
*.snm
*.synctex.gz
*.toc
*.vrb
*.dvi
*.xdv
*.pdfsync
`,
  },
];

export function buildGitignore(ids: string[]): string {
  const seen = new Set<string>();
  const blocks: string[] = [];
  for (const id of ids) {
    const t = TEMPLATES.find(x => x.id === id);
    if (!t) {
      continue;
    }
    if (seen.has(t.id)) {
      continue;
    }
    seen.add(t.id);
    blocks.push(`### ${t.name}\n${t.content.trim()}\n`);
  }
  return blocks.join('\n');
}
